packages:
  - apps/*
  - packages/*

catalog:
  "@cloudflare/workers-types": ^4.20260131.0
  "@libsql/client": 0.15.15
  "@types/node": ^25.2.0
  alchemy: ^0.83.1
  dotenv: ^17.2.3
  libsql: 0.5.22
  typescript: ^5.9.3
  zod: ^4.3.6

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sharp
  - workerd
