export const LOADING_PHRASES = [
  "nyari titik koma yang ilang…",
  "konsultasi sama kerang ajaib…",
  "ngetes sound system: cek, cek…",
  "Kompilasi 1 dan 0 jadi cerita kami…",
  "ngetik nama tamu satu-satu…",
  "nyeting lampu pelaminan…",
  "Dikit lagi beres, siap-siap takjub…",
  "nungguin doa dari Bapak Ibu…",
  "debug hati, hapus drama lama…",
  "ngopi dulu, compile-nya lama…",
  "ngecek cincin: masih aman…",
  "menyimpan momen manis…",
  "doa baik sedang dikirim…",
  "sebentar lagi jadi kenangan…",
] as const;
